name: example
description: A Flutter project for swipe_magic example.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  swipe_magic:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
