name: swipe_magic
description: A Flutter package for Tinder-like swipe cards with smooth animations and customizable interactions. Supports left, right, and up swipe gestures.
version: 1.0.0
publish_to: https://pub.dev/packages/swipe_magic
homepage: https://github.com/AyeshaIftikhar/swipe_magic
repository: https://github.com/AyeshaIftikhar/swipe_magic
issue_tracker: https://github.com/AyeshaIftikhar/swipe_magic/issues
documentation: https://github.com/AyeshaIftikhar/swipe_magic#readme

topics:
  - cards
  - swipe
  - tinder
  - animation
  - gestures

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
